name: centralHorCoord
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - jupyterlab
  - black
  - pytest
  - requests
  - beautifulsoup4
  - pyyaml
  - conda-forge::pre-commit
  - isort
  - pre-commit
  - conda-forge::nb_conda_kernels
  - numpy
  - pandas
  - python-dateutil=2.8.0
  - pytz=2019.3
  - six=

  - pip:
    - python-dotenv
    - flatten-dict
    - ruamel.yaml
    - julia