import Pkg
using Pkg
Pkg.activate("GTheoryJulEnv")
Pkg.add("MathOptInterfaceMosek")
Pkg.add("Ipopt")
Pkg.add("Revise") #Pkg.add(Pkg.PackageSpec(name="Revise", version="3.1.5"))
Pkg.add("Cbc") #Pkg.add(Pkg.PackageSpec(name="Cbc", version="0.7.1"))
Pkg.add("Clp")
Pkg.add("GLPK")
Pkg.add("JuMP")
Pkg.add("Plots")
Pkg.add("PrettyTables")
Pkg.add("SDDP")
Pkg.add("VegaLite")
Pkg.add("CPLEX")
Pkg.add("CSV")
Pkg.add("DataArrays")
Pkg.add("DataFrames")
Pkg.add("Gurobi")
Pkg.add("IJulia")
Pkg.add("Juno")
Pkg.add("MathOptFormat")
Pkg.add("MathOptInterface")
Pkg.add("MathProgBase")
Pkg.add("StatsBase")
Pkg.add("YAML")
Pkg.add("LinearAlgebra")
#=
Pkg.add(Pkg.PackageSpec(name="Clp", version="0.8.1"))
Pkg.add(Pkg.PackageSpec(name="GLPK", version="0.13.0"))
Pkg.add(Pkg.PackageSpec(name="JuMP", version="0.21.3"))
Pkg.add(Pkg.PackageSpec(name="Plots", version="1.6.3"))
Pkg.add(Pkg.PackageSpec(name="PrettyTables", version="0.9.1"))
Pkg.add(Pkg.PackageSpec(name="SDDP", version="0.3.4"))
Pkg.add(Pkg.PackageSpec(name="VegaLite", version="2.3.0"))
Pkg.add(Pkg.PackageSpec(name="CPLEX", version="0.6.1"))
Pkg.add(Pkg.PackageSpec(name="CSV", version="0.5.18"))
Pkg.add(Pkg.PackageSpec(name="DataArrays", version="0.7.0"))
Pkg.add(Pkg.PackageSpec(name="DataFrames", version="0.19.4"))
Pkg.add(Pkg.PackageSpec(name="Gurobi", version="0.7.3"))
Pkg.add(Pkg.PackageSpec(name="IJulia", version="1.20.2"))
Pkg.add(Pkg.PackageSpec(name="Juno", version="0.7.2"))
Pkg.add(Pkg.PackageSpec(name="MathOptFormat", version="0.2.2"))
Pkg.add(Pkg.PackageSpec(name="MathOptInterface", version="0.9.7"))
Pkg.add(Pkg.PackageSpec(name="MathProgBase", version="0.7.7"))
Pkg.add(Pkg.PackageSpec(name="StatsBase", version="0.32.0"))
Pkg.add(Pkg.PackageSpec(name="YAML", version="0.3.2"))
Pkg.add(Pkg.PackageSpec(name="LinearAlgebra"))
=#
Pkg.status()


