import Pkg
using Pkg
Pkg.activate("CentJulEnv")
Pkg.add("MathOptInterfaceMosek")
Pkg.add("Ipopt")
Pkg.add("Revise") #Pkg.add(Pkg.PackageSpec(name="Revise", version="3.1.5"))
Pkg.add("Cbc") #Pkg.add(Pkg.PackageSpec(name="Cbc", version="0.7.1"))
Pkg.add("Clp")
Pkg.add("GLPK")
Pkg.add("JuMP")
Pkg.add("Plots")
Pkg.add("PrettyTables")
Pkg.add("SDDP")
Pkg.add("VegaLite")
Pkg.add("CPLEX")
Pkg.add("CSV")
Pkg.add("DataArrays")
Pkg.add("DataFrames")
Pkg.add("Gurobi")
Pkg.add("IJulia")
Pkg.add("Juno")
Pkg.add("MathOptFormat")
Pkg.add("MathOptInterface")
Pkg.add("MathProgBase")
Pkg.add("StatsBase")
Pkg.add("YAML")
Pkg.add("LinearAlgebra")
Pkg.status()


