name: distHorCoord
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - jupyterlab
  - black
  - pytest
  - requests
  - beautifulsoup4
  - pyyaml
  - conda-forge::pre-commit
  - isort
  - pre-commit
  - conda-forge::nb_conda_kernels
  - numpy=1.17.0
  - pandas=0.25.0
  - python-dateutil=2.8.0
  - pytz=2019.3
  - six=1.12.0

  - pip:
    - python-dotenv
    - flatten-dict
    - ruamel.yaml
    - julia